### ISSUE TITLE
-keep-as3-metadata+=Marshall

### ISSUE THREAD

**Issue by podenphant** [jonnyreeves/as3-vanilla#13]
Please make a note in the documentation that the extract function will fail in release builds unless you add 
-keep-as3-metadata+=Marshall in the compiler options.
Took me a days work to figure out.

I like Vanilla :)

**Comment by podenphant** [comment]
If you use [Transient] as well you need to add that manually as well contarary to what the docs say.
http://help.adobe.com/en_US/Flex/4.0/UsingSDK/WS2db454920e96a9e51e63e3d11c0bf69084-7a92.html

**Comment by jonnyreeves** [comment]
I am not actively maintaining this library anymore, I believe @natami has an active fork, otherwise if you raise a PR that updates the README I will gladly land it for you.

**Comment by natami** [comment]
Sorry, guys!

I'm not active in the AS3 scene anymore ;/

@podenphant  Looking at the fork graph, John's source appears to be a few iterations more advanced than my fork.

- Happy coding ;)
