### ISSUE TITLE
Transient fields aren't ignored

### ISSUE THREAD

**Issue by alebianco** [jonnyreeves/as3-vanilla#2]
fields tagged as [Transient], wich are ignored during serialization, are set to null by as3-vanilla when rebuilding the object.

I forked the project and did a quick fix 'cause I needed it fast, but It would be nice to see this behaviour aligned to the remote/json serialization also on the official release

**Comment by jonnyreeves** [comment]
Thanks!  To be honest, I don't really maintain as3-vanilla anymore as my focus has moved away from ActionScript.  If you would like to submit a pull request, I would be more than happy to merge it through and create a new build.

**Comment by alebianco** [comment]
too bad :(

i'll write some tests specific for the case and then i'll submit the pull request :+1:

**Comment by eamonnfaherty** [comment]
I have added the tests and code for this feature.  

https://github.com/eamonnfaherty/as3-vanilla/

Feel free to grab it.

Eamonn

**Comment by jonnyreeves** [comment]
Cheers Eamonn,

If you make a pull request I can merge it back in for you.

Cheers
Jonny.

**Comment by jonnyreeves** [comment]
Merged @eamonnfaherty's changes into mater and upped the version to 0.1.2 - enjoy!
